### ISSUE TITLE
... has no meta file, but it's in an immutable folder. The asset will be ignored.

### ISSUE THREAD

**Issue by yosun** [Uralstech/UGemini#11]
Just installed in Unity 2022.3.36f1 (and also tried downgrading to 22f1) 
these issues keep occurring - 
has no meta file, but it's in an immutable folder. The asset will be ignored.

**Comment by Uralstech** [comment]
Could you specify the version of UGemini you are using? I assume you are using the preview?

**Comment by Uralstech** [comment]
I've been able to replicate the error in `1.4.0-preview.1` and have fixed it in `1.4.0-preview.2`.
