### ISSUE TITLE
[BUG] TokenCount should be a part of any request call?

### ISSUE THREAD

**Issue by yosun** [Uralstech/UGemini#13]
Trying to understand why a separate async call is necessary to get a token count? Shouldn't token count be part of any response?

**Comment by yosun** [comment]
For example: each chat request should have a token count easily accessible - i believe this is returned as part of the REST API json?

**Comment by Uralstech** [comment]
You do not need to run a separate call to get the token count. Please see [GeminiChatResponse.UsageMetadata](https://uralstech.github.io/UGemini/class_uralstech_1_1_u_gemini_1_1_chat_1_1_gemini_usage_metadata.html). If this is not returning expected values, please let me know.

**Comment by Uralstech** [comment]
`GeminiTokenCountRequest` can be used to check how many tokens a request takes *before* processing the request.
