### ISSUE TITLE
Function Call Sample Script Throws An Error

### ISSUE THREAD

**Issue by ababilinski** [Uralstech/UGemini#51]
**Describe the bug**
When running the [function call sample script](https://github.com/Uralstech/UGemini/blob/fc7ed46e1d0ee0defd2a8a9acebc81345f709aee/UGemini/Packages/com.uralstech.ugemini/Samples~/StreamedFunctionCallingSample/Scripts/StreamingFunctionCallingChatManager.cs#L74) I get the following error:

```
GeminiRequestException: Failed Gemini request: Request Endpoint: /v1beta/models/gemini-1.5-pro:streamGenerateContent | Request Error Code: 400 | Request Error: HTTP/1.1 400 Bad Request | Details:
[{
  "error": {
    "code": 400,
    "message": "Unable to submit request because it has an empty text parameter. Add a value to the parameter and try again. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini",
    "status": "INVALID_ARGUMENT"
  }
}
]
```

**To Reproduce**
1. Go to the sample scene **StreamedFunctionCallingSample > Scenes > Main.unity**
2. Type `Print the text "We are working" to the user console.` in the input field
3. Select the Submit button
4. See the text "We are working" as a response followed by the error.

**Expected behavior**
The chat should output "We are working" and continue the chat without an error.

**Development environment:**
 - Unity version: **2022.3**
 - Build target: **Android**
 - UGemini version: **1.4.0**

**Comment by Uralstech** [comment]
Hi @ababilinski! Thanks for reporting the issue. I tested the same sample in 1.4.0, and it works in the editor on Unity 6000.0.26. I'll test it in a build later and update you if I encounter any errors!

**Comment by Uralstech** [comment]
Okay, since the error shows Gemini 1.5 Pro being used, I changed the sample to use it. I've now been able to replicate the error.

**Comment by Uralstech** [comment]
Okay, I've figured it out:

![Gemini 1.5 Flash](https://github.com/user-attachments/assets/60186597-91d3-4e57-ace6-0d3f44fe45fe)
This is the request sent to Gemini 1.5 *Flash* right after the `printToConsole` function has been called. This is on a custom version of UGemini 2.3.0 that I've been playing around with, but it should be the same JSON generated by 1.4.0, except for the function response object, but that is irrelevant.

![image](https://github.com/user-attachments/assets/9c1bc17d-b08e-4de0-b6d0-a7e9cfc2ae4f)
This is the same, but after I changed the model to Gemini 1.5 *Pro*. You can see it returned an extra `text` ContentPart as part of its first response: `{"parts":[{"functionCall":{"name":"printToConsole","args":{"text":"We are working"}}},{"text":""}],"role":"model"}`. This is the "empty text parameter" mentioned in the exception!

So, if you change [line 82](https://github.com/Uralstech/UGemini/blob/fc7ed46e1d0ee0defd2a8a9acebc81345f709aee/UGemini/Packages/com.uralstech.ugemini/Samples~/StreamedFunctionCallingSample/Scripts/StreamingFunctionCallingChatManager.cs#L82) in the sample to this:
```csharp
contents.Add(new GeminiContent()
{
    Role = response.Candidates[0].Content.Role,
    Parts = new GeminiContentPart[] { response.Parts[0] }
});
```

It should work!
![image](https://github.com/user-attachments/assets/810d9ff4-b3d1-4b47-90f2-b832c4f9012e)

**Comment by ababilinski** [comment]
Thank you so much!
